import { BallCanvas } from './canvas';
import Hero from './Hero';
import Navbar from './Navbar';
import About from './About';
import Tech from './Tech';
import Experience from './Experience';
import Projects from './Projects';
import Contact from './Contact';
import PersonalDevelopment from './PersonalDevelopment';
import Services from './Services';
import SoftSkills from './SoftSkills';
import SingleViewProject from './SingleViewProject';
import SingleViewProjectTech from './SingleViewProjectTech';
export { Hero, Navbar, About, Tech, Experience, Projects, Contact, BallCanvas, PersonalDevelopment, Services,SoftSkills,SingleViewProject, SingleViewProjectTech};
